Repository OZ-Coding-School/oz_react_mini_13, pull requests merged in 2025-09, with the labels that each got.

#31 [mission1] 1단계 미션 구현 - 이찬영/5팀
  .github/pull_request_template.md
  .gitignore
  README.md
  eslint.config.js
  index.html
  package-lock.json
  package.json
  public/vite.svg
  src/App.css
  src/App.jsx
  src/assets/react.svg
  src/components/Layout.jsx
  src/components/MovieCard.jsx
  src/components/MovieDetail.jsx
  src/components/NavBar.jsx
  src/data/movieDetailData.json
  src/data/movieListData.json
  src/index.css
  src/main.jsx
  vite.config.js
Labels: mission-1, 5️⃣

#25 [mission1] 1단계 미션 구현 - 김민우/1팀
  .gitignore
  index.html
  package-lock.json
  package.json
  postcss.config.js
  public/vite.svg
  src/App.jsx
  src/components/Layout.jsx
  src/components/MovieCard.jsx
  src/components/NavBar.jsx
  src/counter.ts
  src/data/movieDetailData.json
  src/data/movieListData.json
  src/main.jsx
  src/main.ts
  src/pages/Home.jsx
  src/pages/MovieDetail.jsx
  src/style.css
  src/typescript.svg
  src/vite-env.d.ts
  tailwind.config.js
  tsconfig.json
  vite.config.js
Labels: mission-1, 1️⃣

#18 [mission1] 1단계 기본 미션 구현 - 윤지예/1팀
  .gitignore
  .prettierrc
  README.md
  commitlint.config.js
  eslint.config.js
  index.html
  package-lock.json
  package.json
  postcss.config.js
  src/App.tsx
  src/components/layout/Layout.tsx
  src/components/layout/NavBar.tsx
  src/components/layout/index.ts
  src/components/movie/MovieCard.tsx
  src/components/movie/MovieCarousel.tsx
  src/components/movie/MovieDetail.tsx
  src/components/movie/MovieList.tsx
  src/components/movie/index.ts
  src/constants/url.ts
  src/data/index.ts
  src/data/movieDetailData.json
  src/data/movieListData.json
  src/index.css
  src/main.tsx
  src/pages/DetailPage.tsx
  src/pages/HomePage.tsx
  src/pages/index.ts
  src/types/movie.ts
  src/vite-env.d.ts
  tailwind.config.js
  tsconfig.app.json
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
Labels: mission-1, 1️⃣

#13 [mission1] 1단계 미션 구현 - 박준서/1팀
  .gitignore
  assets/movieDetailData.json
  assets/movieListData.json
  components/Layout.jsx
  components/MovieCard.jsx
  components/NavBar.jsx
  index.css
  index.html
  package-lock.json
  package.json
  pages/App.jsx
  pages/MovieDetail.jsx
  postcss.config.js
  src/main.jsx
  tailwind.config.js
Labels: mission-1, 1️⃣

#17 [mission 1] 1단계 미션 구현 - 박혜빈 / 3팀
  .gitignore
  README.md
  components.json
  eslint.config.js
  index.html
  jsconfig.json
  package-lock.json
  package.json
  public/vite.svg
  src/App.css
  src/assets/react.svg
  src/components/HeroSwiper.jsx
  src/components/MovieCard.jsx
  src/components/NavBar.jsx
  src/components/ui/button.jsx
  src/components/ui/input.jsx
  src/constants/tmdb.js
  src/data/movieDetailData.json
  src/data/movieListData.json
  src/index.css
  src/layouts/Layout.jsx
  src/lib/utils.js
  src/main.jsx
  src/pages/App.jsx
  src/pages/Login.jsx
  src/pages/MovieDetail.jsx
  src/pages/Signup.jsx
  src/routes/AppRoutes.jsx
  vite.config.js
Labels: mission-1, 3️⃣

#16 [mission1] 1단계 미션 구현 - 이상원 / 3팀
  .gitignore
  eslint.config.js
  index.html
  package-lock.json
  package.json
  postcss.config.cjs
  public/vite.svg
  readme.md
  src/components/Layout.jsx
  src/components/MovieCard.jsx
  src/components/NavBar.jsx
  src/data/movieDetailData.json
  src/data/movieListData.json
  src/index.css
  src/main.jsx
  src/pages/App.jsx
  src/pages/MovieDetail.jsx
  tailwind.config.js
  vite.config.js
Labels: mission-1, 3️⃣

#28 [mission1] 1단계 미션 구현 - 강지훈/4팀
  .gitignore
  .prettierrc
  README.md
  data/movieDetailData.json
  data/movieListData.json
  eslint.config.js
  index.html
  package-lock.json
  package.json
  public/vite.svg
  src/App.tsx
  src/RTK/store.ts
  src/assets/react.svg
  src/components/layout/Header.tsx
  src/components/movie/MovieCard.tsx
  src/components/movie/MovieCarousel.tsx
  src/components/movie/MovieDetail.tsx
  src/components/movie/MovieList.tsx
  src/components/movie/MovieSection.tsx
  src/components/movie/index.ts
  src/constants/tmdb.ts
  src/hooks/useFetchQuery.ts
  src/index.css
  src/main.tsx
  src/pages/Detail.tsx
  src/pages/Main.tsx
  src/pages/index.ts
  src/routes.tsx
  src/types/headerTypes.ts
  src/types/movieDataTypes.ts
  src/vite-env.d.ts
  tailwind.config.ts
  tsconfig.app.json
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
Labels: mission-1, 4️⃣

#27 [mission1] 1단계 미션 구현 - 장제희/4팀
  .gitignore
  README.md
  eslint.config.js
  index.html
  package-lock.json
  package.json
  public/vite.svg
  src/App.css
  src/App.jsx
  src/assets/data/movieDetailData.json
  src/assets/data/movieListData.json
  src/assets/react.svg
  src/component/Layout.jsx
  src/component/MovieCard.jsx
  src/component/MovieDetail.jsx
  src/component/NavBar.jsx
  src/index.css
  src/main.jsx
  vite.config.js
Labels: mission-1, 4️⃣

#6 [mission1] 1단계 미션 구현 - 조다영/4팀
  .github/pull_request_template.md
  .gitignore
  eslint.config.js
  index.html
  package-lock.json
  package.json
  public/vite.svg
  readme.md
  src/App.jsx
  src/App.scss
  src/assets/logo_w.svg
  src/assets/react.svg
  src/data/movieDetailData.json
  src/data/movieListData.json
  src/index.css
  src/main.jsx
  src/pages/Layout.jsx
  src/pages/MovieDetail.jsx
  src/pages/MovieList.jsx
  src/pages/Navbar.jsx
  src/pages/Slider.jsx
  src/utils/constants.js
  vite.config.js
Labels: mission-1, 4️⃣

#46 [mission1] 1단계 미션 구현 - 기정환 / 2팀
  movieSite/.gitignore
  movieSite/README.md
  movieSite/eslint.config.js
  movieSite/index.html
  movieSite/package-lock.json
  movieSite/package.json
  movieSite/src/App.css
  movieSite/src/App.jsx
  movieSite/src/components/Layout.jsx
  movieSite/src/components/MovieCard.jsx
  movieSite/src/components/MovieDetail.jsx
  movieSite/src/data/movieDetailData.json
  movieSite/src/data/movieListData.json
  movieSite/src/index.css
  movieSite/src/main.jsx
  movieSite/vite.config.js
Labels: mission-1, 2️⃣

#21 [mission1] 1단계 미션 구현 - 장동욱 / 5팀
  .gitignore
  README.md
  eslint.config.js
  index.html
  package-lock.json
  package.json
  postcss.config.js
  public/vite.svg
  src/App.css
  src/App.jsx
  src/assets/react.svg
  src/components/HeroBanner.jsx
  src/components/MovieCard.jsx
  src/components/MovieSlider.jsx
  src/components/NavBar.jsx
  src/data/movieDetailData.json
  src/data/movieListData.json
  src/index.css
  src/layouts/MainLayout.jsx
  src/main.jsx
  src/pages/Home.jsx
  src/pages/MovieDetail.jsx
  tailwind.config.js
  vite.config.js
Labels: mission-1, 5️⃣

#49 [mission2] 2단계 미션 구현 - 이상원 / 3팀
  .gitignore
  src/data/movieDetailData.json
  src/data/movieListData.json
  src/pages/App.jsx
  src/pages/MovieDetail.jsx
Labels: mission-2, 3️⃣

#43 [mission2] 2단계 미션 구현 - 박혜빈/3팀
  .gitignore
  package-lock.json
  package.json
  src/App.css
  src/components/Hero.jsx
  src/components/HeroSwiper.jsx
  src/components/MovieCard.jsx
  src/components/NavBar.jsx
  src/components/bits/beams.jsx
  src/components/ui/button.jsx
  src/constants/tmdb.js
  src/pages/App.jsx
  src/pages/MovieDetail.jsx
Labels: mission-2, 3️⃣

#42 [mission2] 2단계 미션 구현 - 박준서/1팀
  .gitignore
  components/MovieCard.jsx
  package-lock.json
  package.json
  pages/App.jsx
  pages/MovieDetail.jsx
  src/api/tmdb.js
  src/main.jsx
Labels: mission-2, 1️⃣

#36 [mission2] 2단계 미션 구현 -윤지예/1팀
  .gitignore
  index.html
  package-lock.json
  package.json
  src/App.tsx
  src/components/common/Carousel.tsx
  src/components/common/SwitchCase.tsx
  src/components/common/index.ts
  src/components/movie/MovieCard.tsx
  src/components/movie/MovieCarousel.tsx
  src/components/movie/MovieDetail.tsx
  src/components/skeleton/CardSkeleton.tsx
  src/components/skeleton/DetailSkeleton.tsx
  src/components/skeleton/index.ts
  src/constants/api.ts
  src/constants/index.ts
  src/constants/url.ts
  src/hooks/useFetch.ts
  src/pages/DetailPage.tsx
  src/pages/HomePage.tsx
  src/utils/api.ts
  src/utils/index.ts
Labels: mission-2, 1️⃣

#66 [mission2] 2단계 미션 구현 - 장제희/4팀
  .gitignore
  src/App.css
  src/App.jsx
  src/component/MovieDetail.jsx
  src/component/NavBar.jsx
Labels: mission-2, 4️⃣

#60 [mission2] 2단계 미션 구현 - 장동욱/5팀
  .gitignore
  src/App.jsx
  src/api/tmdb.js
  src/components/HeroBanner.jsx
  src/components/MovieCard.jsx
  src/components/MovieSlider.jsx
  src/components/NavBar.jsx
  src/components/SkeletonCard.jsx
  src/components/SkeletonDetail.jsx
  src/data/movieDetailData.json
  src/data/movieListData.json
  src/index.css
  src/layouts/MainLayout.jsx
  src/pages/Home.jsx
  src/pages/MovieDetail.jsx
Labels: mission-2, 5️⃣

#71 [mission3] 3단계 미션 구현 - 박혜빈/3팀
  package-lock.json
  package.json
  src/App.css
  src/components/Hero.jsx
  src/components/NavBar.jsx
  src/components/NavBar/AuthButtons.jsx
  src/components/NavBar/Logo.jsx
  src/components/NavBar/NavBar.jsx
  src/components/NavBar/SearchTrigger.jsx
  src/components/command/CommandPalette.jsx
  src/components/ui/command.jsx
  src/components/ui/dialog.jsx
  src/contexts/command-context.js
  src/data/movieDetailData.json
  src/data/movieListData.json
  src/hooks/useDebounce.jsx
  src/layouts/Layout.jsx
  src/lib/api.js
  src/main.jsx
  src/pages/App.jsx
  src/pages/MovieDetail.jsx
  src/pages/Search.jsx
  src/routes/AppRoutes.jsx
  tailwind.config.js
Labels: mission-3, 3️⃣

#70 [mission 3] 3단계 미션 구현 - 황찬진 / 3팀
  index.html
  package-lock.json
  package.json
  src/assets/icons/etc.svg
  src/assets/icons/search.svg
  src/components/common/DebouncingComponent.jsx
  src/components/common/NavBar.jsx
  src/components/common/NotExist.jsx
  src/components/main/MovieCard.jsx
  src/components/main/MovieDetail.jsx
  src/components/main/TopMovieCard.jsx
  src/components/modal/LoginModal.jsx
  src/components/modal/SearchModal.jsx
  src/components/skeleton/CardImgSkeleton.jsx
  src/components/skeleton/DetailImgSkeleton.jsx
  src/lib/hook/useDebounce.js
  src/pages/main.jsx
  src/pages/opening.jsx
  src/routes/AppRoutes.jsx
Labels: mission-3, 3️⃣

#72 [mission3] 3단계 미션 구현 - 권다빈/5팀
  movie-project/component/BestMovies.jsx
  movie-project/component/Layout.jsx
  movie-project/component/Loading.jsx
  movie-project/component/MovieCard.jsx
  movie-project/component/NavBar.jsx
  movie-project/component/NoData.jsx
  movie-project/context/MovieContext.jsx
  movie-project/data/getData.js
  movie-project/data/movieDetailData.json
  movie-project/data/movieListData.json
  movie-project/hooks/useDebounce.js
  movie-project/hooks/useFetch.js
  movie-project/index.html
  movie-project/package-lock.json
  movie-project/package.json
  movie-project/pages/Detail.jsx
  movie-project/pages/Main.jsx
  movie-project/pages/Search.jsx
  movie-project/public/vite.svg
  movie-project/src/App.jsx
  movie-project/src/assets/react.svg
Labels: mission-3, 5️⃣

#76 [mission3] 3단계 미션 구현 - 정예은/5팀
  README.md
  package-lock.json
  package.json
  src/App.jsx
  src/Search.jsx
  src/components/MovieDetail.jsx
  src/components/NavBar.jsx
  src/components/SearchBar.jsx
  src/data/movieApi.js
  src/data/useDebounce.js
  src/hook/useDebounce.js
  src/hook/useSearch.jsx
  src/main.jsx
  src/skeletons/Skeletons.jsx
  src/skeletons/movieDetail.jsx
  src/skeletons/movieList.jsx
Labels: mission-3, 5️⃣

#69 [mission2] 2단계 미션 구현 - 이석민/2팀
  .gitignore
  src/App.jsx
  src/assets/data/tmdbService.js
  src/components/MovieDetail.jsx
  src/components/MovieGrid.jsx
Labels: mission-2, 2️⃣

#65 [mission2] 2단계 미션 구현 - 이원주 / 2팀
  .gitignore
  src/App.jsx
  src/components/MovieCard.jsx
  src/components/MovieDetail.jsx
  src/main.jsx
Labels: mission-2, 2️⃣

#57 [mission 2] 2단계 미션 구현 - 김치훈/2팀
  .gitignore
  package-lock.json
  package.json
  src/api/tmbc.jsx
  src/app/layouts/index.jsx
  src/main.jsx
  src/pages/App.jsx
  src/pages/Layout.jsx
  src/pages/MovieDetail/index.jsx
  src/redux/index.jsx
  src/shared/assets/SVGicons/32pxIcon.jsx
  src/shared/assets/SVGicons/40pxIcon.jsx
  src/shared/hooks/ScrollToTop.jsx
  src/shared/layouts/Navbar/index.jsx
  src/shared/mocks/index.jsx
  src/shared/ui/CastList/index.jsx
  src/shared/ui/MovieCard/index.jsx
  src/shared/ui/MovieDetail/index.jsx
  src/shared/ui/MovieInfoCard/index.jsx
  src/shared/ui/PopularMovies/MovieCard.jsx
  src/shared/ui/PopularMovies/index.jsx
  src/shared/ui/SimilarMovies/index.jsx
  src/shared/ui/Top20Movies/MoviePosterCard.jsx
  src/shared/ui/Top20Movies/index.jsx
  vite.config.js
Labels: mission-2, 2️⃣

#80 [mission3] 3단계 미션 구현 - 장제희/4팀
  package-lock.json
  package.json
  src/App.css
  src/App.jsx
  src/component/MovieCard.jsx
  src/component/MovieDetail.jsx
  src/component/NavBar.jsx
  src/index.css
  vite.config.js
Labels: mission-3, 4️⃣

#79 [mission3] 3단계 미션 구현 - 강지훈/4팀
  src/App.tsx
  src/RTK/searchSlice.ts
  src/RTK/store.ts
  src/RTK/themeSlice.ts
  src/components/layout/Header.tsx
  src/components/movie/MovieBanner.tsx
  src/components/movie/MovieCard.tsx
  src/components/movie/MovieCarousel.tsx
  src/components/movie/MovieDetail.tsx
  src/components/movie/MovieSection.tsx
  src/components/movie/index.ts
  src/components/search/SearchResults.tsx
  src/components/ui/SearchInput.tsx
  src/components/ui/ThemeButton.tsx
  src/constants/tmdb.ts
  src/hooks/useDebounce.ts
  src/index.css
  src/pages/Main.tsx
  src/pages/Search.tsx
  src/routes.tsx
  tailwind.config.ts
Labels: mission-3, 4️⃣

#63 [mission3] 3단계 미션 구현 - 윤지예/1팀
  src/App.tsx
  src/components/common/Carousel.tsx
  src/components/common/Logo.tsx
  src/components/common/SearchInput.tsx
  src/components/common/SwitchCase.tsx
  src/components/common/index.ts
  src/components/layout/Layout.tsx
  src/components/layout/NavBar.tsx
  src/components/movie/MovieCard.tsx
  src/components/movie/MovieList.tsx
  src/components/skeleton/CarouselSkeleton.tsx
  src/components/skeleton/ListSkeleton.tsx
  src/components/skeleton/index.ts
  src/hooks/index.ts
  src/hooks/useDebounce.tsx
  src/hooks/useIntersectionObserver.tsx
  src/pages/DetailPage.tsx
  src/pages/HomePage.tsx
  src/pages/SearchPage.tsx
  src/pages/index.ts
  src/types/movie.ts
  src/utils/api.ts
Labels: mission-3, 1️⃣

#82 [mission-3] 3단계 미션 구현 - 강민/1팀
  README.md
  package-lock.json
  package.json
  src/assets/data/movieDetailData.json
  src/assets/data/movieListData.json
  src/assets/logo1.png
  src/assets/logo2.png
  src/assets/logo3.png
  src/components/Banner.jsx
  src/components/Layout.jsx
  src/components/ModalLayout.jsx
  src/components/MovieCard.jsx
  src/components/MovieCardSkeleton.jsx
  src/components/ScrollToTop.jsx
  src/components/SearchModal.jsx
  src/hooks/useDebounce.js
  src/index.css
  src/lib/dayjs.js
  src/pages/Detail.jsx
  src/pages/Home.jsx
  src/pages/Main.jsx
  src/pages/NotFound.jsx
  src/store/slice.js
  src/store/store.js
  src/store/thunk.js
  src/utils/dataFilter.js
  src/utils/loadingFlag.js
Labels: mission-3, 1️⃣

#88 [mission4] 4단계 미션 구현 - 이상원 / 3팀
  package-lock.json
  package.json
  src/components/FormInput.jsx
  src/components/NavBar.jsx
  src/context/UserContext.jsx
  src/main.jsx
  src/pages/Login.jsx
  src/pages/MovieDetail.jsx
  src/pages/Signup.jsx
  src/supabase/auth/index.js
  src/supabase/auth/useAuth.js
  src/supabase/auth/useEmail.auth.js
  src/supabase/auth/useOauth.auth.js
  src/supabase/context/index.jsx
  src/supabase/index.js
  src/supabase/utilities/config.js
  src/supabase/utilities/dto.js
  src/supabase/utilities/env.js
  src/supabase/utilities/index.js
  src/supabase/utilities/localStorage.js
Labels: mission-4, 3️⃣

#86 [mission4] 4단계 미션 구현 - 박혜빈/3팀
  package-lock.json
  package.json
  src/components/InputField.jsx
  src/components/NavBar/NavBar.jsx
  src/components/NavBar/UserMenu.jsx
  src/components/ui/avatar.jsx
  src/components/ui/card.jsx
  src/components/ui/dropdown-menu.jsx
  src/components/ui/form.jsx
  src/components/ui/label.jsx
  src/contexts/AuthContext.jsx
  src/lib/authSchemas.js
  src/lib/supabase.jsx
  src/main.jsx
  src/pages/Login.jsx
  src/pages/Signup.jsx
  src/pages/user/Favorite.jsx
  src/pages/user/Profile.jsx
  src/pages/user/Setting.jsx
  src/routes/AppRoutes.jsx
  src/routes/RedirectIfAuthed.jsx
  src/routes/RequireAuth.jsx
Labels: mission-4, 3️⃣
